# Site settings
title: StarryPy
description: > # this means to ignore newlines until "baseurl:"
  StarryPy - Python-based server wrappers for Starbound by Chucklefish.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://starrypy.org" # the base hostname & protocol for your site
authors:
  kharidiron:
    name: kharidiron
    bio: Current lead(?) programmer for StarryPy... sorta?
    email: kharidiron@gmail.com
    link: kharidiron

# Build settings
markdown: kramdown
